"""
dosely/scheduler/timing_rules.py
=================================
Resolve DoseSlots → concrete clock times, applying food-relation offsets
and default-rule overrides.

Responsibilities
----------------
1. Anchor resolution:
   Map each DoseSlot.anchor to a base ``datetime.time`` using SchedulerConfig.
   Anchors:  morning → wake_time
             breakfast → breakfast_time
             lunch → lunch_time
             dinner → dinner_time
             bedtime → sleep_time
             as_needed → None (returned as "as needed")
             absolute → slot.absolute_time (recomputed for every-N-hours)

2. Food-relation offset:
   before_food  → −30 min from the meal anchor
   after_food   → +30 min from the meal anchor
   with_food    → ±0 (at meal time)
   empty_stomach→ mapped to "before_food" (−30 min before breakfast)
   any_time/None→ no adjustment

3. "Every N hours" recomputation:
   When slots were generated by frequency_parser with a default wake time,
   timing_rules regenerates them from SchedulerConfig.wake_time.

4. Default rules (applied ONLY when frequency_raw is None):
   PPI / antacid_ppi  → 30 min BEFORE breakfast (single OD slot)
   analgesic_nsaid    → AFTER food (lunch/dinner if BD; all meals if TDS)
   antibiotic         → evenly spaced across waking hours (TDS-like spacing)
   antihistamine      → sedating ones (diphenhydramine, chlorpheniramine,
                        hydroxyzine) at bedtime; non-sedating → OD morning

   Every default output is tagged:  source="default", suggested=True.

Public surface
--------------
    resolve_slots(
        slots: list[DoseSlot],
        config: SchedulerConfig,
        food_relation: str | None,
    ) -> list[tuple[time, str]]           # (resolved_time, instruction)

    apply_default_rule(
        drug_class: str,
        drug_name: str,
        config: SchedulerConfig,
    ) -> list[tuple[time, str]]           # (resolved_time, instruction)
"""

from __future__ import annotations

import math
from datetime import datetime, time, timedelta
from typing import Optional

from dosely.scheduler.models import (
    FOOD_AFTER, FOOD_BEFORE, FOOD_EMPTY, FOOD_WITH, FOOD_ANY,
    SchedulerConfig, DoseSlot,
)

# Antihistamines that are strongly sedating — default to bedtime
_SEDATING_ANTIHISTAMINES: frozenset[str] = frozenset({
    "diphenhydramine",
    "chlorpheniramine",
    "hydroxyzine",
    "promethazine",
    "doxylamine",
    "ketotifen",
})

_FOOD_OFFSETS: dict[str, int] = {
    FOOD_BEFORE: -30,
    FOOD_AFTER:   30,
    FOOD_WITH:     0,
    FOOD_EMPTY:  -30,   # treat as "30 min before" (conventionally before breakfast)
    FOOD_ANY:      0,
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _add_minutes(t: time, minutes: int) -> time:
    """Add ``minutes`` (may be negative) to a ``time``, clamped to 00:00–23:59."""
    base_dt = datetime(2000, 1, 1, t.hour, t.minute)
    dt = base_dt + timedelta(minutes=minutes)
    if dt < datetime(2000, 1, 1, 0, 0):
        return time(0, 0)
    if dt > datetime(2000, 1, 1, 23, 59):
        return time(23, 59)
    return dt.time().replace(second=0, microsecond=0)



def _time_to_str(t: time) -> str:
    return t.strftime("%H:%M")


def _anchor_to_time(anchor: str, cfg: SchedulerConfig, has_food: bool = False) -> Optional[time]:
    """Resolve a DoseSlot anchor name to a clock time."""
    if anchor == "morning":
        return cfg.breakfast_time if has_food else cfg.wake_time
    mapping = {
        "breakfast": cfg.breakfast_time,
        "lunch":     cfg.lunch_time,
        "dinner":    cfg.dinner_time,
        "bedtime":   cfg.sleep_time,
        "as_needed": None,
    }
    return mapping.get(anchor)   # returns None for "as_needed" and unknown


def _food_instruction_text(food_relation: Optional[str], anchor: str) -> str:
    """Build the 'take X food' part of the instruction."""
    if not food_relation or food_relation == FOOD_ANY:
        return ""
    meal_names = {
        "morning": "breakfast",
        "breakfast": "breakfast",
        "lunch": "lunch",
        "dinner": "dinner",
    }
    meal = meal_names.get(anchor, "")
    if meal:
        texts = {
            FOOD_BEFORE: f"30 minutes before {meal}",
            FOOD_AFTER:  f"after {meal}",
            FOOD_WITH:   f"with {meal}",
            FOOD_EMPTY:  "on an empty stomach",
        }
    else:
        texts = {
            FOOD_BEFORE: "30 minutes before food",
            FOOD_AFTER:  "after food",
            FOOD_WITH:   "with food",
            FOOD_EMPTY:  "on an empty stomach",
        }
    return texts.get(food_relation, "")


# ---------------------------------------------------------------------------
# Recompute every-N-hours slots from actual SchedulerConfig
# ---------------------------------------------------------------------------

def _recompute_every_n_hours(
    n_hours: int, cfg: SchedulerConfig
) -> list[tuple[time, str]]:
    """
    Regenerate evenly-spaced slots from cfg.wake_time to cfg.sleep_time.
    """
    if n_hours <= 0:
        return [(cfg.wake_time, "Take as directed")]
    wake_dt  = datetime(2000, 1, 1, cfg.wake_time.hour,  cfg.wake_time.minute)
    sleep_dt = datetime(2000, 1, 1, cfg.sleep_time.hour, cfg.sleep_time.minute)

    count = 0
    curr = wake_dt
    while curr <= sleep_dt:
        count += 1
        curr += timedelta(hours=n_hours)

    count = max(1, count)
    results = []
    curr = wake_dt
    dose_idx = 1
    while curr <= sleep_dt:
        t = curr.time().replace(second=0, microsecond=0)
        instr = f"Take every {n_hours} hours (dose {dose_idx} of {count})"
        results.append((t, instr))
        dose_idx += 1
        curr += timedelta(hours=n_hours)
    return results


# ---------------------------------------------------------------------------
# Public: resolve_slots
# ---------------------------------------------------------------------------

def resolve_slots(
    slots: list[DoseSlot],
    config: SchedulerConfig,
    food_relation: Optional[str],
    every_n_hours: Optional[int] = None,
) -> list[tuple[time, str]]:
    """
    Resolve a list of DoseSlots to (clock_time, instruction_text) tuples.

    Parameters
    ----------
    slots         : from FrequencyResult.slots
    config        : user's daily timetable
    food_relation : FOOD_* constant or None
    every_n_hours : if set, recompute spacing from config (overrides slots)

    Returns
    -------
    List of (time, instruction_str) tuples, sorted by time.
    As-needed slots produce ("as needed", "Take as needed").
    """
    # Special path for every-N-hours
    if every_n_hours is not None:
        return _recompute_every_n_hours(every_n_hours, config)

    results: list[tuple[time, str]] = []
    has_food = food_relation in (FOOD_BEFORE, FOOD_AFTER, FOOD_WITH, FOOD_EMPTY)
    food_offset = _FOOD_OFFSETS.get(food_relation or FOOD_ANY, 0)

    for slot in slots:
        if slot.anchor == "as_needed":
            results.append((time(0, 0), "Take as needed"))
            continue

        if slot.anchor == "absolute" and slot.absolute_time is not None:
            t = slot.absolute_time
            food_text = _food_instruction_text(food_relation, slot.anchor)
            instr = f"Take at {_time_to_str(t)}"
            if food_text:
                instr += f" — {food_text}"
            results.append((t, instr))
            continue

        base = _anchor_to_time(slot.anchor, config, has_food=has_food)
        if base is None:
            results.append((time(0, 0), "Take as needed"))
            continue

        # Apply slot-level offset first (e.g. bedtime dose is exactly at sleep)
        t = _add_minutes(base, slot.offset_minutes)
        # Then apply food-relation offset
        t = _add_minutes(t, food_offset)

        food_text = _food_instruction_text(food_relation, slot.anchor)
        instr_parts = [f"Take at {_time_to_str(t)}"]
        if food_text:
            instr_parts.append(food_text)
        instr = " — ".join(instr_parts)

        results.append((t, instr))

    # Sort by time; as_needed (00:00) sorts first — push to end
    as_needed = [(t, i) for t, i in results if i == "Take as needed"]
    timed     = sorted(
        [(t, i) for t, i in results if i != "Take as needed"],
        key=lambda x: (x[0].hour, x[0].minute),
    )
    return timed + as_needed


# ---------------------------------------------------------------------------
# Public: apply_default_rule
# ---------------------------------------------------------------------------

def apply_default_rule(
    drug_class: str,
    drug_name: str,
    config: SchedulerConfig,
) -> list[tuple[time, str]]:
    """
    Return (time, instruction) pairs applying the hard-coded default rule
    for the given drug class.

    All results produced here must be tagged source="default", suggested=True
    by the caller (scheduler.py).

    Rules
    -----
    antacid_ppi   → 30 min before breakfast, OD
    analgesic_nsaid → after lunch + after dinner (BD default after food)
    antibiotic      → evenly spaced intervals across waking hours
    antihistamine   → sedating → bedtime; non-sedating → morning OD
    other/unknown   → morning OD (safest generic fallback)
    """
    dc = drug_class.lower()
    name_lower = drug_name.lower()

    if dc in ("antacid_ppi", "ppi") or any(
        p in name_lower for p in ("omeprazole", "pantoprazole", "rabeprazole", "esomeprazole", "lansoprazole")
    ):
        t = _add_minutes(config.breakfast_time, -30)
        return [(t, "Take 30 minutes before breakfast — on an empty stomach")]

    if dc in ("analgesic_nsaid", "nsaid") or any(
        n in name_lower for n in ("ibuprofen", "diclofenac", "naproxen", "paracetamol", "aspirin", "aceclofenac")
    ):
        # Default: after lunch and after dinner (BD after food)
        t_lunch  = _add_minutes(config.lunch_time,  30)
        t_dinner = _add_minutes(config.dinner_time, 30)
        return [
            (t_lunch,  "Take after lunch"),
            (t_dinner, "Take after dinner"),
        ]

    if dc in ("antibiotic", "antibiotics") or any(
        a in name_lower for a in ("amoxicillin", "azithromycin", "ciprofloxacin", "metronidazole", "doxycycline")
    ):
        # Evenly spaced intervals across waking hours
        wake_dt  = datetime(2000, 1, 1, config.wake_time.hour,  config.wake_time.minute)
        sleep_dt = datetime(2000, 1, 1, config.sleep_time.hour, config.sleep_time.minute)
        waking_minutes = int((sleep_dt - wake_dt).total_seconds() / 60)
        t1 = config.wake_time
        t2 = (wake_dt + timedelta(minutes=waking_minutes // 2)).time().replace(second=0, microsecond=0)
        t3 = config.sleep_time
        return [
            (t1, "Take at evenly spaced intervals across waking hours (dose 1 of 3)"),
            (t2, "Take at evenly spaced intervals across waking hours (dose 2 of 3)"),
            (t3, "Take at evenly spaced intervals across waking hours (dose 3 of 3)"),
        ]

    if dc in ("antihistamine", "antihistamines"):
        name_parts = name_lower.split()
        is_sedating = (
            any(p in _SEDATING_ANTIHISTAMINES for p in name_parts)
            or any(s in name_lower for s in _SEDATING_ANTIHISTAMINES)
        )
        if is_sedating:
            return [(config.sleep_time, "Take at bedtime — may cause drowsiness")]
        else:
            return [(config.wake_time, "Take in the morning")]

    # Catch-all for "other" / "unknown"
    return [(config.wake_time, "Take in the morning as directed")]

